# Dockerfile
FROM node:20.12.2-alpine

# Set the Intel proxies. These are only required if you need to connect/download anything from the Internet during the build process.
RUN export http_proxy=http://proxy-dmz.intel.com:912 && \
export https_proxy=http://proxy-dmz.intel.com:912 && \
export no_proxy=localhost,127.0.0.0/8,10.0.0.0/8,.intel.com && \
export HTTP_PROXY=http://proxy-dmz.intel.com:912 && \
export HTTPS_PROXY=http://proxy-dmz.intel.com:912 && \
export NO_PROXY=localhost,127.0.0.0/8,10.0.0.0/8,.intel.com && \
npm config set proxy=http://proxy-dmz.intel.com:912  

# Set the working directory  
WORKDIR /usr/src/app  
  
# Copy package.json and package-lock.json  
COPY package*.json ./  
  
# Install dependencies  
RUN npm install  
  
# Copy the application files  
COPY . .  

# Expose the port  
EXPOSE 3333

# Start the application
CMD ["npm", "start"]