version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://backend:4000

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - MONGODB_URL=mongodb://db:27017/duckdb
    volumes:
      - uploads:/app/uploads

  db:
    image: mongo:5.0 # Specifying a version known to support ARM
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver_opts:
      type: none
      device: /mnt/external-hd/mongo-data
      o: bind
  uploads:
    driver_opts:
      type: none
      device: /mnt/external-hd/uploads
      o: bind
