version: '3.8'
services:
  frontend:
    image: localhost:5000/duckolympics-frontend:latest  # Specify the image name with the local registry
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://backend:4000

  backend:
    image: localhost:5000/duckolympics-backend:latest  # Specify the image name with the local registry
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - MONGODB_URL=mongodb://db:27017/duckdb
    volumes:
      - uploads:/app/uploads  # Mounts the uploads directory

  db:
    image: arm64v8/mongo:latest  # Use the ARM-compatible MongoDB image
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  uploads: # Declare the uploads volume here
