version: '3.8'
services:
  frontend:
    image: dedeco133/duckolympics-frontend:latest  # Image pulled from Docker Hub
    container_name: frontend
    ports:
      - "8080:80"  # Map host port 8080 to container port 3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000

  backend:
    image: dedeco133/duckolympics-backend:latest  # Image pulled from Docker Hub
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - MONGODB_URL=mongodb://db:27017/duckdb  # Use the correct service name for MongoDB
    volumes:
      - uploads:/app/uploads  # Mount the uploads directory for persistent storage

  db:
    image: mongo:4.4.18  # Use a specific ARM-compatible MongoDB version
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  mongo-data:
  uploads:
