version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000/api

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MONGODB_URL=mongodb://db:27017/mydatabase
    volumes:
      - uploads:/app/uploads  # Mounts the uploads directory

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  uploads: # Declare the uploads volume here