version: '3.8'
services:
  frontend:
    image: dedeco133/duckolympics-frontend:latest  # Image pulled from Docker Hub
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://backend:4000

  backend:
    image: dedeco133/duckolympics-backend:latest  # Image pulled from Docker Hub
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - MONGODB_URL=mongodb://db:27017/duckdb  # Ensure it uses the correct service name for MongoDB
    volumes:
      - uploads:/app/uploads  # Mounts the uploads directory

  db:
    image: arm64v8/mongo:4.4.18  # Use a specific ARM-compatible MongoDB version
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  uploads: # Declare the uploads volume here
