version: '3.8'
services:
  backend:
    image: dedeco133/duckolympics-backend:latest  # Image pulled from Docker Hub
    container_name: backend
    ports:
      - "4000:4000"  # Expose port 4000 internally (matches the forwarded port on the router)
    depends_on:
      - db
    environment:
      - PORT=4000  # Port the backend listens to
      - MONGODB_URL=mongodb://db:27017/duckdb  # MongoDB connection string
      - UPLOAD_DIR=/app/uploads  # Environment variable for upload directory
      - SSL_KEY_PATH=/app/certs/cadeopato.key  # Path to the SSL private key
      - SSL_CERT_PATH=/app/certs/cadeopato.pem  # Path to the SSL certificate
    volumes:
      - uploads:/app/uploads  # Mount the uploads directory for persistent storage
      - /home/pi/certs:/app/certs  # Mount the certs directory from host to container
    restart: unless-stopped

  db:
    image: mongo:4.4.18  # Use a specific ARM-compatible MongoDB version
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
    restart: unless-stopped

volumes:
  mongo-data:
  uploads:
