name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push multi-platform backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        push: true
        tags: dedeco133/duckolympics-backend:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout only docker-compose.yml
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        sparse-checkout: 'docker-compose.yml'
        
    - name: Pull the latest images
      run:
        docker pull dedeco133/duckolympics-backend:latest

    - name: Deploy with Docker Compose
      run: |
        docker compose down
        docker compose -f ./docker-compose.yml up -d
